version: '3'
services:
  react:
    image: react
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`app.localhost`)"
    depends_on:
      - fastapi
      - traefik

  fastapi:
    image: fastapi
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - ./backend:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.app.localhost`)"
    depends_on:
      - database
      - traefik

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  todo-pgadmin:
    image: "dpage/pgadmin4:5.3"
    depends_on:
      - database
      - traefik
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_PASSWORD_FILE: ${PGADMIN_DEFAULT_PASSWORD_FILE}
      # disable spamming all the screen with logs
      GUNICORN_ACCESS_LOGFILE: /dev/null
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-pgadmin.rule=Host(`dbadmin.localhost`)"

  traefik:
    image: 'traefik:latest'
    container_name: 'traefik'
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=False"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  db_data:
